version: '3'
services:
    udp2raw:
        build: .
        image: xyzrlee/udp2raw
        #restart: unless-stopped
        network_mode: "host"
        cap_add:
            - NET_ADMIN
        command: -s -r 127.0.0.1:3000 -l 127.0.0.1:4000
