version: '3'
services:
    udp2raw:
        build: .
        image: xyzrlee/udp2raw
        #restart: unless-stopped
        ports:
            - 3901:3000/tcp
        cap_add:
            - NET_ADMIN
        volumes:
            - .:/conf:ro
        environment:
            - REMOTEHOST=example.com
            - REMOTEPORT=30000
        command: -s --conf-file /conf/config.conf
