on:
  push:
  workflow_dispatch:

env:
  IMAGE_NAME: udp2raw
  TAG_DEV: dev
  TAG_LATEST: latest
  TAG_CURRENT: v$(date +%Y%m%d)

jobs:
  build:
    name: Deploy to ghcr.io
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: login
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: qemu
      uses: docker/setup-qemu-action@v4
    - name: docker buildx
      uses: docker/setup-buildx-action@v4
    - name: docker matadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{github.repository_owner}}/${{env.IMAGE_NAME}}
        tags: |
          type=raw,value=latest
          type=raw,value=dev
          type=raw,value=v{{date 'YYYYMMDD'}}
    - name: docker build push
      uses: docker/build-push-action@v7
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max
